name: build

on:
  push:
    branches:
      - 'only-vault-and-gas'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint
